language: python 
python: 
- "3.6"
env: 
- DJANGO=2.0 DB=test_guarrizas_db
dist: xenial
services:
  - postgresql
addons:
  postgresql: "9.6"
global:
  - PGPORT=5432
before_install:
- cd decide
install:
  - pip install -r ../requirements.txt
  - pip install codacy-coverage
before_script:
  - cp local_settings.travis.py local_settings.py
  - psql -U postgres -c "create user guarrizas password 'guarrizas'"
  - psql -U postgres -c "create database test_guarrizas_db owner guarrizas"
  - psql -U postgres -c "ALTER USER guarrizas CREATEDB"
  - psql -U postgres -c "ALTER DATABASE test_guarrizas_db OWNER TO guarrizas"
  - psql -U postgres -c "GRANT ALL ON ALL FUNCTIONS IN SCHEMA public to guarrizas"
  - python manage.py migrate
script:
  - python manage.py test
